num1 = input("Enter the first number: ")
num2 = input("Enter teh second number: ")
num3 = input("Enter teh third number: ")
num4 = input("Enter the fourth number: ")
num5 = input("Enter the fifth number: ")
sum = int(num1) + int(num2) + int(num3) +int(num4) + int(num5)
print("The sum of all thr numbers: ", sum)